services:
  postgres:
    image: postgres:14
    container_name: goomer_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=goomermenu
      - POSTGRES_PASSWORD=db1q2w3e4r
      - POSTGRES_DB=goomer_menu 
    restart: always 